apiVersion: batch/v1
kind: Job
metadata:
  name: ecom-db-create
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
      - name: psql-client
        image: postgres:latest
        command: ["bash"]
        args:
          - "-c"
          - |
            psql "host=$POSTGRES_HOST port=5432 user=postgres sslmode=require channel_binding=disable" -c "DROP DATABASE IF EXISTS ecommerce;" &&
            psql "host=$POSTGRES_HOST port=5432 user=postgres sslmode=require channel_binding=disable" -c "CREATE DATABASE ecommerce;"
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_HOST_FQDN
        - name: PGSSLMODE
          value: "require"
        - name: PGCHANNELBINDING
          value: "disable"
      restartPolicy: Never
  backoffLimit: 4