apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations-config
  namespace: ecommerce
data:
  001_init.up.sql: |
    CREATE TABLE public.productcatalog_product (
      id text NOT NULL,
      "name" varchar NOT NULL,
      description varchar NOT NULL,
      thumbnail varchar NOT NULL,
      price_amount int NOT NULL,
      price_currency varchar NOT NULL,
      CONSTRAINT productcatalog_product_pk PRIMARY KEY (id)
    );
  002_cart_cart_tables.up.sql: |
    BEGIN;

    CREATE TABLE public.cart_cart (
      user_id varchar NOT NULL,
      CONSTRAINT cart_cart_pk PRIMARY KEY (user_id)
    );

    CREATE TABLE public.cart_cart_item (
      id varchar NOT NULL,
      cart_id varchar NOT NULL,
      product_id varchar NOT NULL,
      product_name varchar NOT NULL,
      qty float8 NOT NULL,
      price int NOT NULL,
        currency varchar NOT NULL,
      CONSTRAINT cart_cart_item_pk PRIMARY KEY (id),
      CONSTRAINT cart_cart_item_fk FOREIGN KEY (cart_id) REFERENCES public.cart_cart(user_id)
    );

    COMMIT;
  003_auth_tables.up.sql: |
    BEGIN;

    CREATE TABLE public.auth_customer (
      username varchar NOT NULL,
      password_hash varchar NOT NULL,
      CONSTRAINT auth_customer_pk PRIMARY KEY (username)
    );

    CREATE TABLE public.auth_session (
      id varchar NOT NULL,
      customer_id varchar NOT NULL,
      expires_at  timestamp with time zone NOT NULL
    );

    CREATE UNIQUE INDEX auth_session_id_idx ON public.auth_session (id);

    COMMIT;

---
# Migration Job
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: ecommerce
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: migrate/migrate:latest
        command:
          [
            "migrate",
            "-path", "/migrations",
            "-database", "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/ecommerce",
            "-verbose",
            "up"
          ]
        volumeMounts:
        - name: migrations
          mountPath: /migrations
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_HOST
      volumes:
      - name: migrations
        configMap:
          name: migrations-config
      restartPolicy: OnFailure
  backoffLimit: 4
